<?php
$base_path = '';
$page_title = 'Terms & Conditions | Quantum Infoway';
$page_description = 'Terms governing your access to and use of the Quantum Infoway website and its content.';
require_once __DIR__ . '/includes/header.php';
$bp = htmlspecialchars($base_path);
$email = htmlspecialchars(SITE_EMAIL);
$phone = htmlspecialchars(SITE_PHONE);
?>

<main class="page-service page-legal page-legal-premium">
    <section class="hero service-hero legal-hero has-media" id="legal-hero">
        <div class="hero-orbs" aria-hidden="true"><span class="orb orb-1"></span><span class="orb orb-2"></span><span class="orb orb-3"></span></div>
        <div class="hero-particles" id="heroParticles" aria-hidden="true"></div>
        <div class="container hero-inner">
            <div class="hero-content reveal reveal-scale">
                <span class="eyebrow">Legal · Quantum Infoway</span>
                <h1>Terms &amp; <span class="gradient-text">Conditions</span></h1>
                <p class="legal-updated">Effective date: 3 August 2026</p>
                <p>These terms govern your access to and use of the Quantum Infoway website and its content.</p>
                <div class="hero-actions">
                    <a href="#legal-body" class="btn btn-primary btn-lg">Read the terms</a>
                    <a href="<?php echo route_attr('privacy-policy'); ?>" class="btn btn-ghost btn-lg">Privacy Policy</a>
                </div>
                <div class="hero-trust-pills" aria-label="Terms highlights">
                    <span>Site use only</span>
                    <span>Separate client contracts</span>
                    <span>Governed by Indian law</span>
                </div>
            </div>
            <div class="svc-hero-media legal-hero-panel reveal reveal-up" aria-hidden="true">
                <div class="legal-hero-card">
                    <span class="legal-hero-card-label">At a glance</span>
                    <ul>
                        <li>Licence to use the Site</li>
                        <li>IP &amp; acceptable use</li>
                        <li>No scraping / AI training</li>
                        <li>Liability &amp; governing law</li>
                    </ul>
                    <a href="#contact">Contact legal questions →</a>
                </div>
            </div>
        </div>
    </section>

    <nav class="svc-subnav legal-subnav" aria-label="On this page">
        <div class="container svc-subnav-inner">
            <a href="#who">Who we are</a>
            <a href="#licence">Licence</a>
            <a href="#ip">Intellectual property</a>
            <a href="#scraping">Scraping &amp; AI</a>
            <a href="#acceptable">Acceptable use</a>
            <a href="#liability">Liability</a>
            <a href="#contact">Contact</a>
        </div>
    </nav>

    <section class="section" id="legal-body">
        <div class="container legal-layout">
            <aside class="legal-toc reveal reveal-up" aria-label="Contents">
                <strong>Contents</strong>
                <ol>
                    <li><a href="#who">Who we are</a></li>
                    <li><a href="#eligibility">Eligibility</a></li>
                    <li><a href="#licence">Licence to use the Site</a></li>
                    <li><a href="#ip">Intellectual property</a></li>
                    <li><a href="#scraping">Automated access &amp; AI</a></li>
                    <li><a href="#acceptable">Acceptable use</a></li>
                    <li><a href="#advice">Content is information</a></li>
                    <li><a href="#submissions">Submissions</a></li>
                    <li><a href="#third-party">Third-party sites</a></li>
                    <li><a href="#disclaimer">Disclaimer</a></li>
                    <li><a href="#liability">Limitation of liability</a></li>
                    <li><a href="#indemnity">Indemnity</a></li>
                    <li><a href="#changes">Changes</a></li>
                    <li><a href="#termination">Termination</a></li>
                    <li><a href="#law">Governing law</a></li>
                    <li><a href="#general">General</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ol>
            </aside>

            <article class="legal-panel legal-prose reveal reveal-up">
                <p class="legal-lead">This document is an electronic record generated by a computer system and does not require any physical or digital signature. It is published in accordance with the Information Technology Act, 2000 and the rules made under it. This is a legal agreement between you and Quantum Infoway governing your access to and use of the Site.</p>

                <h2 id="who">1. Who we are and what these terms cover</h2>
                <p>This website (the “Site”) is owned and operated by Quantum Infoway (“Quantum Infoway”, “we”, “us”, or “our”), a technology services company with its principal place of business in India.</p>
                <p>These Terms &amp; Conditions (“Terms”) govern your access to and use of the Site and its content. By accessing or using the Site, you agree to be bound by these Terms and by our <a href="<?php echo route_attr('privacy-policy'); ?>">Privacy Policy</a>, which is incorporated into these Terms by reference. If you do not agree, please do not use the Site.</p>
                <p>These Terms govern the Site only. Any services we provide to clients are governed by separate written agreements, such as a master services agreement, statement of work, or proposal, and nothing on this Site forms part of any such agreement unless expressly stated in it. The Site is an informational and marketing website. It does not require you to create or maintain an account, and we do not process payments or financial transactions through it.</p>

                <h2 id="eligibility">2. Eligibility and jurisdiction</h2>
                <p>The Site is intended for business audiences. It is not directed to any person or entity in any jurisdiction where its publication or availability would be contrary to law, or would subject Quantum Infoway to any registration or licensing requirement. You are responsible for compliance with the laws that apply to you.</p>

                <h2 id="licence">3. Licence to use the Site</h2>
                <p>Subject to these Terms, we grant you a limited, revocable, nonexclusive, and nontransferable licence to access and view the Site and its content for your personal or internal business evaluation purposes. We may suspend or terminate this licence at any time. No other right or licence is granted.</p>

                <h2 id="ip">4. Intellectual property</h2>
                <p>All content on the Site, including text, articles, guides, case studies, graphics, images, logos, page layouts, design elements, calculators, and software, is owned by Quantum Infoway or its licensors and is protected by copyright, trademark, and other intellectual property laws of India and other countries.</p>
                <p>You may not copy, reproduce, republish, distribute, transmit, display, perform, license, sell, or create derivative works from any Site content without our prior written consent, except for brief quotations with clear attribution and a link to the source page. The Quantum Infoway name and logo are trademarks of Quantum Infoway and may not be used without written permission. Third-party product names that appear on the Site are trademarks of their respective owners and are used for identification only.</p>
                <p>For paid client engagements, ownership of custom deliverables and source code is as set out in the applicable written contract.</p>

                <h2 id="scraping">5. Automated access, scraping, and AI training</h2>
                <p>We welcome good-faith indexing of the Site by search engines and answer engines that respect our robots.txt directives and attribute content to its source.</p>
                <p>Except as expressly permitted by our robots.txt file or by a separate written licence from us, you may not:</p>
                <ul>
                    <li>access the Site by automated means, including bots, scrapers, crawlers, or spiders, in any manner that exceeds or disregards our robots.txt directives;</li>
                    <li>carry out bulk extraction, harvesting, or text and data mining of Site content;</li>
                    <li>use any Site content to train, fine-tune, or otherwise develop any artificial intelligence or machine learning model, system, or dataset, whether or not the resulting output is commercial, without our prior written consent; or</li>
                    <li>circumvent any technical measure that controls access to the Site.</li>
                </ul>
                <p>Our robots.txt file and any other machine-readable signals we publish are an express reservation of rights for the purposes of applicable text and data mining laws, and not a waiver of any right.</p>

                <h2 id="acceptable">6. Acceptable use</h2>
                <p>You agree that you will not:</p>
                <ul>
                    <li>use the Site for any unlawful purpose or in violation of any applicable law or regulation;</li>
                    <li>interfere with or disrupt the operation, security, or availability of the Site, or attempt to do so;</li>
                    <li>probe, scan, or test the vulnerability of the Site or any related system or network without written authorisation;</li>
                    <li>misrepresent your identity or affiliation in any submission to us, or submit information that is false, misleading, or infringing; or</li>
                    <li>use any content or feature of the Site to build a product or service that competes with the Site itself.</li>
                </ul>

                <h2 id="advice">7. Content is information, not advice</h2>
                <p>The content on this Site, including blog articles, guides, pricing estimates, calculators, statistics, and case studies, is provided for general information only. It does not constitute professional, technical, legal, financial, or any other advice, and it is not a substitute for advice tailored to your situation. Cost figures and calculator outputs are indicative estimate ranges, not offers or quotations, and any engagement is subject to a separately agreed scope and contract. Case study results describe specific past projects and are not a promise of similar outcomes. No client or professional relationship is created by reading the Site or by contacting us through it.</p>

                <h2 id="submissions">8. Submissions through the Site</h2>
                <p>When you submit information through our contact form or other channels on the Site, you confirm that the information is accurate and that you are authorised to share it. Our handling of personal information in such submissions is described in our <a href="<?php echo route_attr('privacy-policy'); ?>">Privacy Policy</a>. Ideas, feedback, or suggestions you choose to send us about the Site or our services may be used by us without restriction or obligation, except for personal information, which is always handled under the Privacy Policy.</p>

                <h2 id="third-party">9. Third-party sites and services</h2>
                <p>The Site contains links to third-party websites and services, including review platforms, social networks, messaging apps, and scheduling tools. These are provided for convenience only. We do not control and are not responsible for the content, availability, terms, or privacy practices of any third party. Your use of any third-party site or service is at your own risk and subject to the terms of that third party.</p>

                <h2 id="disclaimer">10. Disclaimer of warranties</h2>
                <p>The Site and all content on it are provided on an “as is” and “as available” basis, without representation or warranty of any kind, express or implied, including warranties of accuracy, completeness, currency, merchantability, fitness for a particular purpose, noninfringement, uninterrupted availability, or freedom from viruses or other harmful components. Content may contain inaccuracies or become outdated, and we are under no obligation to update it. Some jurisdictions do not allow the exclusion of certain warranties, so parts of this section may not apply to you.</p>

                <h2 id="liability">11. Limitation of liability</h2>
                <p>To the maximum extent permitted by applicable law, Quantum Infoway, its directors, officers, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, business, goodwill, data, or anticipated savings, arising out of or in connection with your use of, or inability to use, the Site or any content on it, even if advised of the possibility of such damages.</p>
                <p>To the maximum extent permitted by applicable law, the total aggregate liability of Quantum Infoway arising out of or relating to the Site or these Terms shall not exceed INR 5,000 (five thousand Indian Rupees). Nothing in these Terms excludes or limits any liability that cannot be excluded or limited under applicable law.</p>
                <p>Liability for paid project work is governed exclusively by the signed engagement contract.</p>

                <h2 id="indemnity">12. Indemnity</h2>
                <p>You agree to indemnify and hold harmless Quantum Infoway, its directors, officers, employees, and affiliates from and against any claims, liabilities, damages, losses, costs, and expenses, including reasonable legal fees, arising out of or related to your breach of these Terms, your violation of any law or third-party right, or your misuse of the Site.</p>

                <h2 id="changes">13. Changes to the Site and to these Terms</h2>
                <p>We may change, suspend, or discontinue any part of the Site at any time without notice. We may also amend these Terms from time to time. When we make material changes, we will post the updated Terms on this page with a new effective date, and the update will apply from the date of posting. Your continued use of the Site after an updated version is posted constitutes acceptance of the updated Terms. We encourage you to review this page periodically.</p>

                <h2 id="termination">14. Termination</h2>
                <p>We may suspend or terminate your access to the Site at any time, with or without cause, and without liability. Sections of these Terms that by their nature should survive termination, including intellectual property, disclaimers, limitation of liability, indemnity, and governing law, survive any termination.</p>

                <h2 id="law">15. Governing law and dispute resolution</h2>
                <p>These Terms and any dispute arising out of or in connection with the Site shall be governed by the laws of India, without regard to conflict of law principles. The parties shall first attempt in good faith to resolve any dispute through written communication. Subject to that, the courts in India shall have exclusive jurisdiction over all disputes arising under or in connection with these Terms or the Site.</p>

                <h2 id="general">16. General</h2>
                <p>If any provision of these Terms is held invalid or unenforceable, the remaining provisions remain in full force. Our failure to enforce any provision is not a waiver of it. These Terms, together with the Privacy Policy, are the entire agreement between you and Quantum Infoway regarding use of the Site. We are not liable for any failure to perform due to causes beyond our reasonable control.</p>

                <h2 id="contact">17. Contact</h2>
                <p>Questions about these Terms can be sent to <a href="mailto:<?php echo $email; ?>"><?php echo $email; ?></a>, by phone at <a href="tel:+918511108041"><?php echo $phone; ?></a>, or via our <a href="<?php echo route_attr('contact-us'); ?>">contact page</a>.</p>
                <p class="legal-cross">Also see our <a href="<?php echo route_attr('privacy-policy'); ?>">Privacy Policy</a>.</p>
            </article>
        </div>
    </section>

    <section class="section dark-band" id="legal-cta">
        <div class="container">
            <div class="service-cta-band has-rays reveal reveal-up">
                <img class="cta-rays" src="<?php echo htmlspecialchars($base_path); ?>assets/images/services/brand__light-rays-effect-bg.webp" alt="" aria-hidden="true">
                <h2>Ready to talk about a project?</h2>
                <p>Share what you are building. We respond within one business day.</p>
                <a href="<?php echo route_attr('contact-us'); ?>" class="btn btn-primary btn-lg">Talk to an Expert</a>
            </div>
        </div>
    </section>
</main>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
