<?php
/**
 * Enterprise Solutions case study content (web / mobile / web-only).
 */

if (!function_exists('case_studies_all')) {
    function case_studies_all(): array
    {
        static $cases = null;
        if ($cases !== null) {
            return $cases;
        }

        $cases = [
            /* ——— EV WEB ——— */
            'ev-charger-installation' => [
                'slug' => 'ev-charger-installation',
                'platform' => 'web',
                'pair_slug' => 'ev-charger-installation-mobile',
                'hub_group' => 'ev-charger',
                'title' => 'EV Charger Installation — Web Platform',
                'short_title' => 'EV Installation Web Platform',
                'hub_title' => 'EV Charger Installation Management',
                'industry' => 'Electric Vehicle Infrastructure',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Centralized command center for dealers, vendors, inventory, approvals, and installation analytics.',
                'overview' => 'We designed the web operations layer that orchestrates the full EV charger installation lifecycle. OEM admins, dealers, and vendors run onboarding, kit allocation, work orders, multi-level approvals, and enterprise reporting from one cloud portal — while field execution syncs from companion mobile apps.',
                'overview_extra' => 'The web platform replaces email chains, spreadsheets, and paper job cards with a single system of record for every installation order.',
                'challenge_intro' => 'EV manufacturers scaled charger rollouts faster than their back-office tools. Coordination broke down between dealers, vendors, and HQ — with no live view of kits, inspections, or approvals.',
                'solution_intro' => 'A role-based web portal that digitizes dealer/vendor management, order orchestration, inventory, inspection review, and analytics — tightly integrated with field mobile apps.',
                'hero_image' => 'assets/images/case-studies/ev-charger-installation-web-hero.png',
                'dashboard_image' => 'assets/images/case-studies/ev-charger-installation-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/ev-charger-installation-web-dashboard.png',
                'mobile_screens_image' => null,
                'accent' => '#2f6bff',
                'challenges' => [
                    'No centralized installation order desk',
                    'Dealer–vendor assignment done manually',
                    'Kit and charger inventory invisible to HQ',
                    'Inspection reports stuck in email threads',
                    'Multi-level approvals delayed by days',
                    'No live SLA or productivity dashboards',
                    'Customer feedback never reached OEM reports',
                    'Audit packs assembled by hand for compliance',
                ],
                'solution' => 'Built an enterprise web portal covering dealer/vendor onboarding, installation order management, kit warehouse control, inspection approval queues, dealer verification, final sign-off, and network-wide analytics.',
                'workflow' => [
                    'Dealer creates Installation Order',
                    'Customer & Vehicle Registration',
                    'Kit Allocation from Warehouse',
                    'Vendor Assignment',
                    'Electrician Dispatch (via mobile)',
                    'Inspection Review & Approval',
                    'Schedule Confirmation',
                    'Field Execution Sync',
                    'Dealer Verification',
                    'Final OEM Approval',
                    'Order Closure & Reports',
                ],
                'modules' => [
                    'Dealer Management' => ['Onboarding & KYC', 'Approval workflows', 'Performance scorecards', 'Inventory entitlements'],
                    'Vendor Management' => ['Vendor onboarding', 'Capacity planning', 'Assignment rules', 'SLA monitoring'],
                    'Order Management' => ['Installation orders', 'Work orders', 'Scheduling board', 'Escalation rules'],
                    'Inspection Desk' => ['Safety checklist review', 'Photo evidence gallery', 'Approve / rework loops'],
                    'Inventory & Warehouse' => ['EV kits', 'Chargers & accessories', 'Stock transfer', 'Low-stock alerts'],
                    'Reports & Analytics' => ['Dealer / vendor reports', 'Cycle-time KPIs', 'CSAT trends', 'Executive dashboards'],
                ],
                'role_journeys' => [
                    ['role' => 'OEM Admin', 'journey' => 'Configures network rules → monitors live jobs → clears final approvals → exports compliance packs'],
                    ['role' => 'Dealer Ops', 'journey' => 'Creates order → allocates kit → verifies completion photos → confirms customer satisfaction'],
                    ['role' => 'Vendor Manager', 'journey' => 'Accepts assignment → allocates electrician → tracks SLA → closes vendor invoice trail'],
                ],
                'roles' => [
                    ['name' => 'OEM Admin', 'desc' => 'Network governance, policies, and final approvals'],
                    ['name' => 'Dealer Ops', 'desc' => 'Orders, kits, verification, and customer handoff'],
                    ['name' => 'Vendor Manager', 'desc' => 'Crew capacity and job acceptance'],
                    ['name' => 'Finance / Audit', 'desc' => 'Exportable trails for settlement and compliance'],
                ],
                'integrations' => ['OEM ERP inventory sync', 'CRM dealer master', 'Maps geocoding', 'SMS / email notification gateway', 'Document object storage'],
                'security' => ['RBAC with least-privilege roles', 'Immutable audit log', 'Signed evidence attachments', 'SSO-ready enterprise login'],
                'delivery_highlights' => ['Cloud-native multi-tenant ready', 'API-first for mobile companions', 'Week-scale module releases', 'ISO-aligned access controls'],
                'tech_stack' => ['React', 'Next.js', 'Node.js', 'Laravel', 'PostgreSQL', 'Redis', 'AWS', 'S3', 'Map APIs'],
                'mobile_apps' => [],
                'features' => [
                    'Multi-level Approval Desk',
                    'Live Operations Dashboard',
                    'Kit Warehouse Control',
                    'Inspection Evidence Review',
                    'Dealer Performance Analytics',
                    'Role-based Access',
                    'Notification Orchestration',
                    'Exportable Audit Packs',
                ],
                'benefits' => [
                    'Single source of truth for every installation',
                    'Faster dealer–vendor coordination',
                    'Full inventory visibility',
                    'Audit-ready approval history',
                    'Executive-ready KPI reporting',
                ],
                'results' => [
                    ['70%', 'Faster end-to-end cycle'],
                    ['100%', 'Digital order trail'],
                    ['1', 'Central ops workspace'],
                    ['40%', 'Less coordination overhead'],
                ],
                'future_scope' => [
                    'AI scheduling recommendations for vendor load',
                    'Predictive kit replenishment',
                    'OEM ERP two-way sync for financials',
                    'Customer self-service appointment portal',
                    'IoT post-install charger health feeds',
                ],
                'related' => ['ev-charger-installation-mobile', 'dealer-management-system', 'vehicle-exchange-platform'],
            ],

            /* ——— EV MOBILE ——— */
            'ev-charger-installation-mobile' => [
                'slug' => 'ev-charger-installation-mobile',
                'platform' => 'mobile',
                'pair_slug' => 'ev-charger-installation',
                'hub_group' => 'ev-charger',
                'title' => 'EV Charger Installation — Mobile Apps',
                'short_title' => 'EV Installation Mobile Apps',
                'hub_title' => 'EV Charger Installation Management',
                'industry' => 'Electric Vehicle Infrastructure',
                'eyebrow' => 'Mobile Apps Case Study',
                'platform_label' => 'Mobile Apps',
                'tagline' => 'Field-first apps for electricians, vendors, dealers, and customers — GPS, photos, signatures, and live status.',
                'overview' => 'We built a suite of mobile applications that execute the installation on site. Electricians run inspections and installs with GPS verification and photo evidence; dealers and vendors track jobs; customers receive status and capture signatures and feedback — all syncing to the web command center.',
                'overview_extra' => 'Mobile eliminates paper job sheets, missed geo-proof, and delayed status updates from the field.',
                'challenge_intro' => 'Field teams worked offline from HQ systems. Photos lived on personal phones, GPS proof was missing, and customers had no transparent status — creating disputes and rework.',
                'solution_intro' => 'Role-specific native-quality apps with geo-fencing, camera workflows, digital signatures, QR kit scanning, and push notifications tied to the web order lifecycle.',
                'hero_image' => 'assets/images/case-studies/ev-charger-installation-mobile-hero.png',
                'dashboard_image' => null,
                'admin_image' => null,
                'mobile_screens_image' => 'assets/images/case-studies/ev-charger-installation-mobile-screens.png',
                'accent' => '#2f6bff',
                'challenges' => [
                    'Paper checklists on job sites',
                    'No GPS proof of attendance',
                    'Photos not linked to work orders',
                    'Customers unaware of ETAs',
                    'Signatures collected on paper',
                    'Rework from incomplete evidence',
                    'Electrician productivity untracked',
                    'Push updates missing for dealers',
                ],
                'solution' => 'Delivered Electrician, Dealer, Vendor, and Customer apps covering job queues, navigation, site inspection, installation execution, QR scanning, geo-fencing, time tracking, signatures, and feedback.',
                'workflow' => [
                    'Job assigned to electrician',
                    'Navigate to site (GPS)',
                    'Geo-fence check-in',
                    'Site inspection checklist',
                    'Photo evidence capture',
                    'QR scan installation kit',
                    'Execute installation steps',
                    'Time tracking',
                    'Customer digital signature',
                    'Customer feedback',
                    'Sync to web for approval',
                ],
                'modules' => [
                    'Electrician App' => ['Job queue', 'GPS & geo-fence', 'Inspection checklist', 'Photo evidence', 'QR kit scan', 'Time tracking'],
                    'Dealer App' => ['Order status', 'Verification prompts', 'Push alerts', 'Customer handoff'],
                    'Vendor App' => ['Crew assignments', 'Live job board', 'SLA timers'],
                    'Customer App' => ['Appointment status', 'Technician ETA', 'Signature & feedback'],
                ],
                'role_journeys' => [
                    ['role' => 'Electrician', 'journey' => 'Accept job → check-in → inspect → install with evidence → collect signature → sync'],
                    ['role' => 'Customer', 'journey' => 'Track ETA → review work → sign digitally → rate experience'],
                    ['role' => 'Dealer', 'journey' => 'Watch live status → verify completion pack → close customer loop'],
                ],
                'roles' => [
                    ['name' => 'Electrician', 'desc' => 'Field execution with GPS and evidence'],
                    ['name' => 'Vendor Lead', 'desc' => 'Crew dispatch from mobile'],
                    ['name' => 'Dealer', 'desc' => 'Mobile verification and alerts'],
                    ['name' => 'Customer', 'desc' => 'Status, signature, and feedback'],
                ],
                'integrations' => ['Web order API', 'Push notifications (FCM)', 'Maps & routing', 'Camera / gallery pipeline', 'Offline sync queue'],
                'security' => ['Device session controls', 'Signed media uploads', 'Role-scoped job visibility', 'Encrypted transit'],
                'delivery_highlights' => ['Flutter cross-platform apps', 'Offline-tolerant job cache', 'Background sync', 'Shared design system with web'],
                'tech_stack' => ['Flutter', 'Dart', 'Firebase', 'Node.js APIs', 'PostgreSQL', 'AWS S3', 'Google Maps', 'FCM'],
                'mobile_apps' => ['Electrician App', 'Dealer App', 'Vendor App', 'Customer App'],
                'features' => [
                    'Real-time Job Tracking',
                    'GPS Verification',
                    'Geo-fencing',
                    'Photo Evidence',
                    'Digital Signature',
                    'QR Code Scanning',
                    'Push Notifications',
                    'Offline Sync',
                ],
                'benefits' => [
                    'Proof-rich field execution',
                    'Fewer customer disputes',
                    'Higher first-time-right installs',
                    'Live visibility for dealers',
                    'Faster approval packages',
                ],
                'results' => [
                    ['4.8★', 'Avg. customer rating'],
                    ['100%', 'Jobs with GPS proof'],
                    ['35%', 'Less field rework'],
                    ['Real-time', 'Dealer visibility'],
                ],
                'future_scope' => [
                    'AR guidance for charger mounting',
                    'Voice notes auto-transcribed to tickets',
                    'Smart route optimization for crews',
                    'Wearable check-in for high-safety sites',
                    'In-app spare-part reordering',
                ],
                'related' => ['ev-charger-installation', 'vehicle-exchange-platform-mobile', 'vehicle-auction-management-mobile'],
            ],

            /* ——— DMS WEB-ONLY ——— */
            'dealer-management-system' => [
                'slug' => 'dealer-management-system',
                'platform' => 'web-only',
                'pair_slug' => null,
                'hub_group' => 'dms',
                'title' => 'Enterprise Dealer Management System',
                'short_title' => 'Dealer Management System',
                'hub_title' => 'Dealer Management System',
                'industry' => 'Automotive Distribution',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Dealer lifecycle on one portal — onboarding, agreements, planning, inventory, compliance, and exit.',
                'overview' => 'We built a comprehensive Dealer Lifecycle Management web platform covering every stage from registration to resignation. Legal agreements, multi-level approvals, FY business planning, inventory allocation, and performance analytics run in a single enterprise portal.',
                'overview_extra' => 'Networks standardize dealer operations without paper binders or fragmented regional tools.',
                'challenge_intro' => 'Dealer onboarding was slow, agreements were paper-based, and planning lived in disconnected spreadsheets — making compliance and network visibility nearly impossible.',
                'solution_intro' => 'An enterprise DMS portal with document vaults, e-signature, approval chains, annual/monthly planning, inventory allocation, and KPI scorecards.',
                'hero_image' => 'assets/images/case-studies/dealer-management-system-hero.png',
                'dashboard_image' => 'assets/images/case-studies/dealer-management-system-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/dealer-management-system-admin-portal.png',
                'mobile_screens_image' => null,
                'accent' => '#6d4df6',
                'challenges' => [
                    'Manual dealer onboarding',
                    'Paper agreements and wet signatures',
                    'No structured approval workflow',
                    'Compliance gaps across regions',
                    'Poor inventory visibility',
                    'FY planning in spreadsheets',
                    'No network-wide performance view',
                    'Exit / resignation handled ad hoc',
                ],
                'solution' => 'Created a dealer lifecycle web platform with automated onboarding, document management, digital agreements, multi-level approvals, inventory allocation, business planning, and compliance analytics.',
                'workflow' => [
                    'Dealer Registration',
                    'Document Upload & KYC',
                    'Legal Verification',
                    'Multi-Level Approval',
                    'Agreement & Digital Signature',
                    'Dealer Activation',
                    'Inventory Allocation',
                    'FY / Monthly Business Planning',
                    'Performance Tracking',
                    'Renewal',
                    'Resignation & Exit Approval',
                    'Archive',
                ],
                'modules' => [
                    'Onboarding' => ['Registration', 'Document vault', 'Legal clearance', 'Activation'],
                    'Agreements' => ['Templates', 'Review cycles', 'E-signature', 'Renewals'],
                    'Business Planning' => ['Full FY planning', 'Month-wise targets', 'Product & revenue forecast', 'Budget & KPIs'],
                    'Inventory' => ['Allocation', 'Stock visibility', 'Transfer requests'],
                    'Compliance & Analytics' => ['Policy checks', 'Scorecards', 'Network benchmarks', 'Audit trails'],
                ],
                'role_journeys' => [
                    ['role' => 'Network Admin', 'journey' => 'Opens onboarding → routes legal → activates dealer → monitors compliance'],
                    ['role' => 'Regional Manager', 'journey' => 'Approves dealers → coaches FY plans → reviews scorecards'],
                    ['role' => 'Dealer Principal', 'journey' => 'Uploads docs → signs agreement → submits plans → tracks inventory'],
                ],
                'roles' => [
                    ['name' => 'Network Admin', 'desc' => 'Governance and activations'],
                    ['name' => 'Legal', 'desc' => 'Agreement and compliance clearance'],
                    ['name' => 'Regional Manager', 'desc' => 'Approvals and performance coaching'],
                    ['name' => 'Dealer Principal', 'desc' => 'Planning inputs and portal operations'],
                ],
                'integrations' => ['DocuSign / e-sign', 'ERP inventory', 'HR dealer master', 'BI / Power BI exports', 'Object storage'],
                'security' => ['RBAC', 'Document watermarking hooks', 'Full approval audit', 'Encrypted document store'],
                'delivery_highlights' => ['Paperless activation path', 'Planning modules for FY + monthly', 'Network KPI dashboards', 'Exit archival workflow'],
                'tech_stack' => ['React', 'TypeScript', 'Node.js', 'Java Spring Boot', 'PostgreSQL', 'AWS S3', 'E-Sign API', 'Power BI'],
                'mobile_apps' => [],
                'features' => ['Multi-level Approval', 'Digital Agreement', 'Role Management', 'Business Planning', 'Inventory Tracking', 'Analytics Dashboard', 'Compliance Alerts'],
                'benefits' => ['Paperless dealer management', 'Faster activation', 'Better compliance', 'Accurate planning', 'Centralized operations'],
                'results' => [['60%', 'Faster activation'], ['100%', 'Paperless agreements'], ['3×', 'Planning accuracy'], ['1', 'Network portal']],
                'future_scope' => ['AI dealer risk scoring', 'Auto renewal recommendations', 'Territory optimization', 'DMS–ERP deep sync', 'Dealer knowledge hub'],
                'related' => ['ev-charger-installation', 'vehicle-exchange-platform', 'invoice-management-system'],
            ],

            /* ——— T&E WEB-ONLY ——— */
            'travel-expense-management' => [
                'slug' => 'travel-expense-management',
                'platform' => 'web-only',
                'pair_slug' => null,
                'hub_group' => 'te',
                'title' => 'Corporate Travel & Expense Management',
                'short_title' => 'Travel & Expense Management',
                'hub_title' => 'Travel & Expense Management',
                'industry' => 'Enterprise HR & Finance',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Travel requests, advances, claims, receipts, and finance reimbursement — fully digital approval chains.',
                'overview' => 'We delivered a centralized Travel & Expense web platform that automates trip planning, advances, expense claims, department approvals, finance verification, and reimbursement reporting with a complete audit trail.',
                'overview_extra' => 'Employees and finance share one policy-aware workspace instead of email attachments and spreadsheet trackers.',
                'challenge_intro' => 'Reimbursements were slow, receipts went missing, and finance lacked a trustworthy audit trail across departments.',
                'solution_intro' => 'A T&E portal with policy checks, multi-level e-approvals, receipt vaults, advance tracking, and finance settlement dashboards.',
                'hero_image' => 'assets/images/case-studies/travel-expense-management-hero.png',
                'dashboard_image' => 'assets/images/case-studies/travel-expense-management-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/travel-expense-management-admin-portal.png',
                'mobile_screens_image' => null,
                'accent' => '#2f6bff',
                'challenges' => [
                    'Manual reimbursement cycles',
                    'Slow multi-department approvals',
                    'Missing or unclear receipts',
                    'Advance requests hard to track',
                    'Weak finance audit trails',
                    'Inconsistent expense categories',
                    'Policy exceptions discovered late',
                    'No consolidated spend analytics',
                ],
                'solution' => 'Built a corporate T&E web system for travel requests, advances, claims, miscellaneous expenses, receipt management, e-decision approvals, finance verification, and reporting.',
                'workflow' => [
                    'Travel Request',
                    'Manager Approval',
                    'Advance Request',
                    'Travel Execution',
                    'Expense Submission',
                    'Receipt Upload',
                    'Department e-Decision',
                    'Finance Verification',
                    'Reimbursement',
                    'Reports & Audit Export',
                ],
                'modules' => [
                    'Travel Planning' => ['Trips', 'Itineraries', 'Policy validation'],
                    'Advances' => ['Request', 'Disbursement', 'Settlement against claims'],
                    'Expense Claims' => ['Categories', 'Line items', 'Fx support'],
                    'Approvals' => ['Manager', 'Department head', 'Finance queues'],
                    'Finance Desk' => ['Exceptions', 'Settlement status', 'Audit packs'],
                ],
                'role_journeys' => [
                    ['role' => 'Employee', 'journey' => 'Request trip → take advance → submit claims with receipts → track payout'],
                    ['role' => 'Manager', 'journey' => 'Review policy flags → approve / reject → escalate outliers'],
                    ['role' => 'Finance', 'journey' => 'Verify → settle → export audit for controllers'],
                ],
                'roles' => [
                    ['name' => 'Employee', 'desc' => 'Trips, advances, and claims'],
                    ['name' => 'Manager', 'desc' => 'Policy-aware approvals'],
                    ['name' => 'Department Head', 'desc' => 'Budget control'],
                    ['name' => 'Finance', 'desc' => 'Verification and reimbursement'],
                ],
                'integrations' => ['SSO / SAML', 'OCR receipt hooks', 'Payroll / AP export', 'Email alerts', 'ERP cost centers'],
                'security' => ['Role-based queues', 'Immutable claim history', 'Attachment malware scanning hooks', 'Segregation of duties'],
                'delivery_highlights' => ['Department workflow engine', 'OCR-ready receipts', 'Finance settlement KPIs', 'Full audit export'],
                'tech_stack' => ['React', 'Node.js', 'Laravel', 'MySQL', 'AWS', 'OCR APIs', 'SSO'],
                'mobile_apps' => [],
                'features' => ['Multi-level Approval', 'Department Workflow', 'Expense Categories', 'Receipt Vault', 'Notifications', 'Spend Analytics', 'Audit Trail'],
                'benefits' => ['Faster settlement', 'Less paperwork', 'Stronger financial control', 'Complete audit trail'],
                'results' => [['55%', 'Faster settlement'], ['80%', 'Less paperwork'], ['100%', 'Digital audit'], ['30%', 'Fewer exceptions']],
                'future_scope' => ['Card feed auto-match', 'Policy AI flags', 'Booking integrations', 'Multi-entity consolidation', 'Trip carbon tracking'],
                'related' => ['invoice-management-system', 'dealer-management-system', 'ev-charger-installation'],
            ],

            /* ——— INVOICE WEB-ONLY ——— */
            'invoice-management-system' => [
                'slug' => 'invoice-management-system',
                'platform' => 'web-only',
                'pair_slug' => null,
                'hub_group' => 'invoice',
                'title' => 'Enterprise Invoice Management System',
                'short_title' => 'Invoice Management System',
                'hub_title' => 'Invoice Management System',
                'industry' => 'Finance & Procurement',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Vendor invoice intake, OCR-ready validation, multi-level approval, payments, and audit history.',
                'overview' => 'We developed a Vendor Invoice Management web platform that streamlines submission, verification, department and multi-level approvals, payment processing, and reporting while preserving financial compliance.',
                'overview_extra' => 'AP, procurement, and vendors operate from one queue with role-based controls and immutable logs.',
                'challenge_intro' => 'Invoice processing was slow and error-prone — documents scattered, approvals opaque, and payment status unclear to vendors.',
                'solution_intro' => 'An AP workspace with vendor portal intake, validation, approval orchestration, payment tracking, and audit-ready reporting.',
                'hero_image' => 'assets/images/case-studies/invoice-management-system-hero.png',
                'dashboard_image' => 'assets/images/case-studies/invoice-management-system-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/invoice-management-system-admin-portal.png',
                'mobile_screens_image' => null,
                'accent' => '#6d4df6',
                'challenges' => [
                    'Manual invoice data entry',
                    'Inconsistent document validation',
                    'Slow multi-level approvals',
                    'Opaque payment status',
                    'Weak vendor self-service',
                    'Incomplete audit history',
                    'Duplicate invoice risk',
                    'No aging visibility for AP',
                ],
                'solution' => 'Built an enterprise invoice platform for vendor registration, OCR-ready submission, finance review, department approval, payment processing, closure, and dashboards.',
                'workflow' => [
                    'Vendor Registration',
                    'Invoice Submission',
                    'Document Validation',
                    'Finance Review',
                    'Department Approval',
                    'Multi-Level Approval',
                    'Payment Processing',
                    'Invoice Closure',
                    'Reports',
                ],
                'modules' => [
                    'Vendor Portal' => ['Onboarding', 'Bank details', 'Submission status'],
                    'Invoice Desk' => ['Intake', 'Line validation', 'Exception handling'],
                    'Approvals' => ['Finance', 'Department', 'Multi-level chains'],
                    'Payments' => ['Schedules', 'Remittance', 'Status tracking'],
                    'Audit & Reports' => ['Aging', 'Vendor spend', 'Immutable logs'],
                ],
                'role_journeys' => [
                    ['role' => 'Vendor', 'journey' => 'Register → submit invoice → track payment'],
                    ['role' => 'AP Clerk', 'journey' => 'Validate → route exceptions → prepare payment batch'],
                    ['role' => 'Controller', 'journey' => 'Approve → authorize payment → review audit'],
                ],
                'roles' => [
                    ['name' => 'Vendor', 'desc' => 'Portal submission and status'],
                    ['name' => 'AP Clerk', 'desc' => 'Intake and exceptions'],
                    ['name' => 'Finance Controller', 'desc' => 'Authorization'],
                    ['name' => 'Department Approver', 'desc' => 'Cost-center confirmation'],
                ],
                'integrations' => ['OCR engine', 'ERP connectors', 'Bank payment files', 'Email notifications', 'Object storage'],
                'security' => ['Segregation of duties', 'Immutable audit', 'Vendor access scoping', 'Approval tamper evidence'],
                'delivery_highlights' => ['OCR-ready intake', 'Vendor self-service', 'Payment tracking', 'Aging analytics'],
                'tech_stack' => ['React', 'Node.js', 'Java Spring Boot', 'PostgreSQL', 'AWS', 'OCR', 'ERP APIs'],
                'mobile_apps' => [],
                'features' => ['OCR Ready', 'Invoice Verification', 'Role-based Approval', 'Payment Tracking', 'Vendor Portal', 'Financial Reports'],
                'benefits' => ['Reduced processing time', 'Improved accuracy', 'Centralized AP', 'Complete audit history'],
                'results' => [['50%', 'Faster cycle'], ['95%', 'Straight-through accuracy'], ['1', 'AP workspace'], ['100%', 'Audit coverage']],
                'future_scope' => ['3-way PO/GRN match', 'Early-payment discounts', 'Bank file automation', 'Duplicate anomaly AI', 'Multi-currency treasury'],
                'related' => ['travel-expense-management', 'dealer-management-system', 'ev-charger-installation'],
            ],

            /* ——— EXCHANGE WEB ——— */
            'vehicle-exchange-platform' => [
                'slug' => 'vehicle-exchange-platform',
                'platform' => 'web',
                'pair_slug' => 'vehicle-exchange-platform-mobile',
                'hub_group' => 'exchange',
                'title' => 'Vehicle Exchange — Web Platform',
                'short_title' => 'Vehicle Exchange Web',
                'hub_title' => 'Vehicle Exchange Platform',
                'industry' => 'Automotive Retail',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Trade-in desk for valuation, approvals, inventory, and resale — unified across dealership networks.',
                'overview' => 'The web platform is the dealership control tower for pre-owned exchange: customer and vehicle records, valuation engines, offer approvals, inventory boards, and resale pipelines — fed by field inspection apps.',
                'overview_extra' => 'Pricing discipline and stock visibility become consistent across every location.',
                'challenge_intro' => 'Trade-ins were inconsistent: inspections varied, valuations were subjective, and used inventory was hard to see across the network.',
                'solution_intro' => 'A retail ops web portal for exchange offers, approval workflows, pricing controls, inventory aging, and resale analytics.',
                'hero_image' => 'assets/images/case-studies/vehicle-exchange-platform-web-hero.png',
                'dashboard_image' => 'assets/images/case-studies/vehicle-exchange-platform-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/vehicle-exchange-platform-web-dashboard.png',
                'mobile_screens_image' => null,
                'accent' => '#2f6bff',
                'challenges' => [
                    'Fragmented trade-in desks',
                    'Subjective pricing without comps',
                    'Slow offer approvals',
                    'Poor used-stock visibility',
                    'Disconnected resale pipelines',
                    'No aging alerts on inventory',
                    'Inconsistent vehicle history capture',
                    'Margin leakage on exchanges',
                ],
                'solution' => 'Delivered a vehicle exchange web platform for dealer/customer masters, valuation, offer approvals, inventory control, sales pipeline, and analytics — integrated with inspector mobile apps.',
                'workflow' => [
                    'Dealer & Customer Registration',
                    'Vehicle Registration',
                    'Inspection pack received',
                    'Valuation & Pricing',
                    'Offer Approval',
                    'Exchange Offer Issued',
                    'Inventory Listing',
                    'Resale Pipeline',
                    'Delivery & Closure',
                    'Margin Reports',
                ],
                'modules' => [
                    'Customer & Vehicle' => ['Profiles', 'VIN registry', 'History notes'],
                    'Valuation Desk' => ['Pricing engine', 'Market comps', 'Offer builder'],
                    'Approvals' => ['Manager / dealer admin sign-off'],
                    'Inventory' => ['Stock board', 'Aging alerts', 'Transfers'],
                    'Sales & Analytics' => ['Resale pipeline', 'Turn rates', 'Margin KPIs'],
                ],
                'role_journeys' => [
                    ['role' => 'Valuation Analyst', 'journey' => 'Opens inspection pack → prices → drafts offer → routes approval'],
                    ['role' => 'Dealer Admin', 'journey' => 'Approves offer → lists inventory → monitors aging'],
                    ['role' => 'Sales Lead', 'journey' => 'Works resale pipeline → closes delivery'],
                ],
                'roles' => [
                    ['name' => 'Dealer Admin', 'desc' => 'Offers and location control'],
                    ['name' => 'Valuation Analyst', 'desc' => 'Pricing and comps'],
                    ['name' => 'Inventory Manager', 'desc' => 'Stock and aging'],
                    ['name' => 'Sales Lead', 'desc' => 'Resale pipeline'],
                ],
                'integrations' => ['Pricing / market APIs', 'DMS inventory', 'Image store from mobile', 'CRM customers', 'Finance payouts'],
                'security' => ['Offer approval RBAC', 'Price change audit', 'Documented vehicle history', 'Scoped dealer tenancy'],
                'delivery_highlights' => ['Pricing engine', 'Network inventory board', 'Approval workflow', 'Margin analytics'],
                'tech_stack' => ['React', 'Node.js', 'PostgreSQL', 'AWS', 'Pricing APIs', 'S3'],
                'mobile_apps' => [],
                'features' => ['Vehicle History', 'Pricing Engine', 'Approval Workflow', 'Inventory Control', 'Analytics', 'Multi-location View'],
                'benefits' => ['Faster trade-in desk', 'Better valuation accuracy', 'Higher inventory visibility', 'Stronger margins'],
                'results' => [['45%', 'Faster trade-in cycle'], ['25%', 'Better valuation accuracy'], ['Real-time', 'Stock visibility'], ['Higher', 'Conversion']],
                'future_scope' => ['Listing syndication', 'Dynamic market index', 'Cross-dealer transfers', 'F&I bundling', 'AI price suggestions'],
                'related' => ['vehicle-exchange-platform-mobile', 'vehicle-auction-management', 'dealer-management-system'],
            ],

            /* ——— EXCHANGE MOBILE ——— */
            'vehicle-exchange-platform-mobile' => [
                'slug' => 'vehicle-exchange-platform-mobile',
                'platform' => 'mobile',
                'pair_slug' => 'vehicle-exchange-platform',
                'hub_group' => 'exchange',
                'title' => 'Vehicle Exchange — Mobile Apps',
                'short_title' => 'Vehicle Exchange Mobile',
                'hub_title' => 'Vehicle Exchange Platform',
                'industry' => 'Automotive Retail',
                'eyebrow' => 'Mobile Apps Case Study',
                'platform_label' => 'Mobile Apps',
                'tagline' => 'Inspector and sales apps for on-lot checklists, photo evidence, and instant offer handoff.',
                'overview' => 'Mobile apps power the frontline of vehicle exchange: structured inspections with photo evidence, condition grades, and sales consultant flows that push complete packs to the web valuation desk in minutes.',
                'overview_extra' => 'Every trade-in starts with consistent field data — not sticky notes and ad-hoc camera rolls.',
                'challenge_intro' => 'Inspectors used paper checklists; photos were incomplete; sales teams could not trigger valuation until someone typed everything into a desktop.',
                'solution_intro' => 'Inspector and Sales Consultant apps with guided checklists, mandatory photo sets, VIN capture, and live sync to the web platform.',
                'hero_image' => 'assets/images/case-studies/vehicle-exchange-platform-mobile-hero.png',
                'dashboard_image' => null,
                'admin_image' => null,
                'mobile_screens_image' => 'assets/images/case-studies/vehicle-exchange-platform-mobile-screens.png',
                'accent' => '#2f6bff',
                'challenges' => [
                    'Paper inspection sheets',
                    'Missing mandatory photos',
                    'VIN / condition typos',
                    'Delayed handoff to pricing',
                    'No GPS / timestamp proof',
                    'Sales follow-up outside the system',
                    'Inconsistent grade scales',
                    'Rework when web desk rejects packs',
                ],
                'solution' => 'Shipped Inspector and Sales Consultant mobile apps covering VIN intake, guided checklists, photo evidence, condition grading, and instant sync for valuation.',
                'workflow' => [
                    'Start inspection on mobile',
                    'Capture VIN & vehicle basics',
                    'Guided checklist',
                    'Mandatory photo set',
                    'Condition grade',
                    'Submit pack to web',
                    'Sales tracks offer status',
                    'Customer update from app',
                ],
                'modules' => [
                    'Inspector App' => ['VIN capture', 'Checklist', 'Photo evidence', 'Grades', 'Submit pack'],
                    'Sales Consultant App' => ['Customer intake', 'Offer status', 'Follow-ups', 'Delivery checklist'],
                ],
                'role_journeys' => [
                    ['role' => 'Inspector', 'journey' => 'Open job → checklist → photos → grade → submit'],
                    ['role' => 'Sales Consultant', 'journey' => 'Log customer → watch valuation → communicate offer'],
                ],
                'roles' => [
                    ['name' => 'Inspector', 'desc' => 'Structured field inspection'],
                    ['name' => 'Sales Consultant', 'desc' => 'Customer and offer follow-up'],
                ],
                'integrations' => ['Web valuation API', 'Camera pipeline', 'Push status', 'Offline draft cache'],
                'security' => ['Job-scoped access', 'Signed media', 'Device auth'],
                'delivery_highlights' => ['Guided photo sets', 'Offline draft inspections', 'Instant web sync', 'Shared grade taxonomy'],
                'tech_stack' => ['Flutter', 'Firebase', 'Node.js APIs', 'S3', 'FCM'],
                'mobile_apps' => ['Inspector App', 'Sales Consultant App'],
                'features' => ['Inspection Checklist', 'Photo Evidence', 'VIN Capture', 'Condition Grades', 'Push Status', 'Offline Drafts'],
                'benefits' => ['Consistent inspections', 'Faster valuation handoff', 'Fewer rejected packs', 'Better customer updates'],
                'results' => [['50%', 'Faster inspection packs'], ['90%', 'Complete photo sets'], ['Lower', 'Desk rework'], ['Higher', 'Offer trust']],
                'future_scope' => ['AI damage detection', 'Voice defect notes', 'AR panel guides', 'Customer co-browse photos'],
                'related' => ['vehicle-exchange-platform', 'ev-charger-installation-mobile', 'vehicle-auction-management-mobile'],
            ],

            /* ——— AUCTION WEB ——— */
            'vehicle-auction-management' => [
                'slug' => 'vehicle-auction-management',
                'platform' => 'web',
                'pair_slug' => 'vehicle-auction-management-mobile',
                'hub_group' => 'auction',
                'title' => 'Vehicle Auction — Web Platform',
                'short_title' => 'Vehicle Auction Web',
                'hub_title' => 'Vehicle Auction Management',
                'industry' => 'Automotive Auction',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Single and bulk lot auctions with scheduling, live bid ops, payments, allocation, and analytics.',
                'overview' => 'The auction web platform manages the full lifecycle: vehicle listing, bidder registration and KYC, live bid operations, reserve rules, winner confirmation, payment collection, allocation, and post-auction reporting.',
                'overview_extra' => 'Organizations run transparent, competitive auctions for single vehicles and bulk lots from one control room.',
                'challenge_intro' => 'Offline auctions lacked transparency, bulk lots were hard to manage, and post-sale settlement reporting was fragmented.',
                'solution_intro' => 'A digital auction control room with lot setup, live monitoring, payment tracking, and analytics — paired with bidder mobile apps.',
                'hero_image' => 'assets/images/case-studies/vehicle-auction-management-web-hero.png',
                'dashboard_image' => 'assets/images/case-studies/vehicle-auction-management-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/vehicle-auction-management-web-dashboard.png',
                'mobile_screens_image' => null,
                'accent' => '#6d4df6',
                'challenges' => [
                    'Opaque offline bidding',
                    'Weak bulk lot tooling',
                    'Manual bid validation',
                    'Slow winner confirmation',
                    'Fragmented payments',
                    'Thin post-auction reports',
                    'No reserve / increment controls',
                    'Limited bidder KYC tracking',
                ],
                'solution' => 'Built a secure auction web platform for listings, bidder management, live bid ops, reserve pricing, payments, allocation, delivery, and analytics.',
                'workflow' => [
                    'Vehicle Registration',
                    'Inspection Pack',
                    'Auction Listing',
                    'Bidder Registration & KYC',
                    'Bid Approval',
                    'Live Auction Ops',
                    'Highest Bid Selection',
                    'Winner Confirmation',
                    'Payment Collection',
                    'Vehicle Allocation',
                    'Delivery',
                    'Reports',
                ],
                'modules' => [
                    'Auction Ops' => ['Scheduling', 'Single & bulk lots', 'Reserve rules'],
                    'Bidder Desk' => ['Registration', 'KYC', 'Approvals'],
                    'Live Floor' => ['Bid monitor', 'Increments', 'Alerts'],
                    'Payments' => ['Deposits', 'Settlement', 'Refunds'],
                    'Analytics' => ['Price discovery', 'Lot performance', 'Audit trail'],
                ],
                'role_journeys' => [
                    ['role' => 'Auction Admin', 'journey' => 'Create lot → set reserve → monitor live → confirm winner'],
                    ['role' => 'Finance', 'journey' => 'Collect deposit → settle → release allocation'],
                    ['role' => 'Logistics', 'journey' => 'Allocate vehicle → schedule delivery'],
                ],
                'roles' => [
                    ['name' => 'Auction Admin', 'desc' => 'Lots, rules, live oversight'],
                    ['name' => 'Finance', 'desc' => 'Deposits and settlement'],
                    ['name' => 'Logistics', 'desc' => 'Allocation and delivery'],
                    ['name' => 'Compliance', 'desc' => 'Bidder KYC audit'],
                ],
                'integrations' => ['WebSocket bid stream', 'Payment gateway', 'CDN media', 'ERP settlement', 'Notification service'],
                'security' => ['Bidder KYC gates', 'Bid audit log', 'Role-separated ops', 'Payment reconciliation'],
                'delivery_highlights' => ['Single + bulk lots', 'Live bid control room', 'Reserve & auto-increment', 'Full digital audit'],
                'tech_stack' => ['React', 'WebSockets', 'Node.js', 'Redis', 'PostgreSQL', 'AWS', 'Payment Gateway'],
                'mobile_apps' => [],
                'features' => ['Single & Bulk Auction', 'Live Bid Ops', 'Reserve Price', 'Auto Increment', 'Payment Tracking', 'Auction Analytics', 'RBAC'],
                'benefits' => ['Transparent process', 'Faster disposal', 'Better price discovery', 'Digital audit trail'],
                'results' => [['2×', 'Faster disposal'], ['Higher', 'Price discovery'], ['Live', 'Ops transparency'], ['100%', 'Audit trail']],
                'future_scope' => ['Proxy-max strategies', 'Multi-currency', 'Streaming lot video', 'Private dealer auctions', 'Secondary relist automation'],
                'related' => ['vehicle-auction-management-mobile', 'vehicle-exchange-platform', 'dealer-management-system'],
            ],

            /* ——— AUCTION MOBILE ——— */
            'vehicle-auction-management-mobile' => [
                'slug' => 'vehicle-auction-management-mobile',
                'platform' => 'mobile',
                'pair_slug' => 'vehicle-auction-management',
                'hub_group' => 'auction',
                'title' => 'Vehicle Auction — Mobile Apps',
                'short_title' => 'Vehicle Auction Mobile',
                'hub_title' => 'Vehicle Auction Management',
                'industry' => 'Automotive Auction',
                'eyebrow' => 'Mobile Apps Case Study',
                'platform_label' => 'Mobile Apps',
                'tagline' => 'Bidder and auction-ops apps for live bidding, watchlists, deposits, and on-floor control.',
                'overview' => 'Mobile experiences bring bidders into live auctions with real-time increments and notifications, while ops staff manage floor actions and lot readiness from handheld devices synced to the web control room.',
                'overview_extra' => 'Competitive bidding becomes accessible anywhere — without losing auditability.',
                'challenge_intro' => 'Bidders could not participate remotely with confidence; ops staff lacked handheld tools during live events; payment prompts were delayed.',
                'solution_intro' => 'Bidder and Auction Ops mobile apps with live bid streaming, auto-increment UX, watchlists, deposit prompts, and floor checklists.',
                'hero_image' => 'assets/images/case-studies/vehicle-auction-management-mobile-hero.png',
                'dashboard_image' => null,
                'admin_image' => null,
                'mobile_screens_image' => 'assets/images/case-studies/vehicle-auction-management-mobile-screens.png',
                'accent' => '#6d4df6',
                'challenges' => [
                    'No remote live bidding',
                    'Missed bid notifications',
                    'Clunky deposit collection',
                    'Ops tied to desktop only',
                    'Watchlist management absent',
                    'Winner alerts delayed',
                    'Floor checklist on paper',
                    'Poor bidder engagement',
                ],
                'solution' => 'Launched Bidder and Auction Ops apps for live lots, bid placement, auto-increment, notifications, deposits, and floor readiness synced to web.',
                'workflow' => [
                    'Bidder login & KYC status',
                    'Browse / watch lots',
                    'Join live auction',
                    'Place / auto-increment bid',
                    'Receive outbid alerts',
                    'Win confirmation',
                    'Pay deposit from app',
                    'Ops confirms floor allocation',
                ],
                'modules' => [
                    'Bidder App' => ['Lot browse', 'Live bid', 'Watchlist', 'Alerts', 'Deposits'],
                    'Auction Ops App' => ['Floor checklist', 'Lot readiness', 'Live assist', 'Allocation prompts'],
                ],
                'role_journeys' => [
                    ['role' => 'Bidder', 'journey' => 'Watch lot → bid live → get alerts → pay deposit'],
                    ['role' => 'Floor Ops', 'journey' => 'Mark lot ready → assist live → trigger allocation'],
                ],
                'roles' => [
                    ['name' => 'Bidder', 'desc' => 'Live participation and payments'],
                    ['name' => 'Auction Ops', 'desc' => 'Floor readiness and assists'],
                ],
                'integrations' => ['WebSocket bids', 'Push (FCM)', 'Payment SDK', 'Web allocation API'],
                'security' => ['KYC-gated bidding', 'Device session limits', 'Bid receipt tokens'],
                'delivery_highlights' => ['Live bid latency focus', 'Outbid push alerts', 'Deposit in-app', 'Ops handheld mode'],
                'tech_stack' => ['Flutter', 'WebSockets', 'Firebase', 'Payment SDK', 'Redis'],
                'mobile_apps' => ['Bidder App', 'Auction Ops App'],
                'features' => ['Live Bid Tracking', 'Auto Bid Increment', 'Bid Notifications', 'Watchlists', 'In-app Deposits', 'Floor Ops Mode'],
                'benefits' => ['Broader bidder reach', 'Higher engagement', 'Faster deposits', 'Smoother live floors'],
                'results' => [['↑', 'Remote participation'], ['Faster', 'Deposit collection'], ['Live', 'Outbid alerts'], ['Lower', 'Floor errors']],
                'future_scope' => ['Proxy bidding', 'Lot video stream', 'AR lot preview', 'Multi-currency bids'],
                'related' => ['vehicle-auction-management', 'vehicle-exchange-platform-mobile', 'ev-charger-installation-mobile'],
            ],

            /* ——— CLASSIC: E-COMMERCE ——— */
            'ecommerce-platform' => [
                'slug' => 'ecommerce-platform',
                'platform' => 'web-only',
                'pair_slug' => null,
                'hub_group' => 'ecommerce',
                'title' => 'Full-Scale E-Commerce Platform',
                'short_title' => 'E-Commerce Platform',
                'hub_title' => 'Full-Scale E-Commerce Platform',
                'industry' => 'E-Commerce / Retail',
                'eyebrow' => 'Web Platform Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Conversion-focused storefront with custom checkout, inventory sync, and marketing integrations.',
                'overview' => 'A growing retail brand needed a fast, conversion-focused online store. We delivered a complete WooCommerce-based storefront with optimized checkout, real-time inventory and order management, SEO-ready architecture, and marketing integrations built for scale.',
                'overview_extra' => 'The result was a store that loads faster, converts better, and gives operations a single source of truth for catalog and orders.',
                'challenge_intro' => 'The brand’s previous storefront was slow, hard to extend, and disconnected from inventory and campaigns — leaking conversions at checkout.',
                'solution_intro' => 'We rebuilt the commerce experience end-to-end: performance, checkout UX, inventory sync, and growth tooling — without sacrificing day-to-day ops control.',
                'hero_image' => 'assets/images/portfolio5.jpg',
                'dashboard_image' => 'assets/images/case-studies/ecommerce-platform-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/ecommerce-platform-admin-portal.png',
                'mobile_screens_image' => null,
                'accent' => '#2f6bff',
                'challenges' => [
                    'Slow page loads hurting SEO and ads ROI',
                    'Checkout abandonment from friction and errors',
                    'Inventory out of sync across channels',
                    'Limited promotion and coupon flexibility',
                    'Weak analytics for product and funnel decisions',
                    'Manual order ops and refund handling',
                ],
                'solution' => 'Built a full-scale e-commerce platform with custom WooCommerce themes and flows, optimized checkout, real-time inventory sync, marketing integrations, and an admin console for catalog, orders, and reporting.',
                'workflow' => [
                    'Catalog & product setup',
                    'Inventory sync',
                    'Customer browse & search',
                    'Cart & checkout',
                    'Payment capture',
                    'Order confirmation',
                    'Fulfillment & shipping',
                    'Returns / refunds',
                    'Campaign & analytics review',
                ],
                'modules' => [
                    'Storefront' => ['Product pages', 'Collections', 'Search & filters', 'Wishlist'],
                    'Checkout' => ['Custom checkout UX', 'Coupons', 'Tax & shipping', 'Payment gateways'],
                    'Inventory' => ['Stock sync', 'Low-stock alerts', 'Multi-warehouse hooks'],
                    'Orders' => ['Order desk', 'Fulfillment status', 'Refunds'],
                    'Marketing' => ['Email / SMS hooks', 'UTM tracking', 'Promo engine'],
                    'Admin & Reports' => ['Sales dashboards', 'Product performance', 'Export packs'],
                ],
                'role_journeys' => [
                    ['role' => 'Shopper', 'journey' => 'Browse → add to cart → checkout → track order'],
                    ['role' => 'Store Ops', 'journey' => 'Sync stock → process orders → handle refunds'],
                    ['role' => 'Marketing', 'journey' => 'Launch promo → measure funnel → optimize ROAS'],
                ],
                'roles' => [
                    ['name' => 'Customer', 'desc' => 'Browse, purchase, and track orders'],
                    ['name' => 'Store Admin', 'desc' => 'Catalog, inventory, and order ops'],
                    ['name' => 'Marketing', 'desc' => 'Campaigns and conversion tracking'],
                    ['name' => 'Finance', 'desc' => 'Settlements and refund oversight'],
                ],
                'integrations' => ['Payment gateways', 'Shipping APIs', 'Email / SMS', 'Analytics & pixels', 'Inventory feeds'],
                'security' => ['PCI-aware payment flow', 'Role-based admin', 'Secure customer accounts', 'Audit of refunds'],
                'delivery_highlights' => ['Conversion-focused UX', 'SEO-ready architecture', 'Real-time inventory', '99.9% uptime posture'],
                'tech_stack' => ['WordPress', 'WooCommerce', 'PHP', 'MySQL', 'Redis', 'CDN', 'Payment APIs'],
                'mobile_apps' => [],
                'features' => ['Optimized Checkout', 'Inventory Sync', 'Promo Engine', 'SEO Architecture', 'Order Desk', 'Sales Analytics'],
                'benefits' => ['Higher conversions', 'Faster page loads', 'Reliable inventory', 'Cleaner ops for orders'],
                'results' => [['45%', 'More conversions'], ['2×', 'Faster page loads'], ['99.9%', 'Uptime'], ['1', 'Unified commerce desk']],
                'future_scope' => ['Headless storefront option', 'Personalization engine', 'Subscription products', 'Marketplace seller mode'],
                'related' => ['operations-management-web-app', 'customer-facing-mobile-app', 'invoice-management-system'],
            ],

            /* ——— CLASSIC: OPS WEB APP ——— */
            'operations-management-web-app' => [
                'slug' => 'operations-management-web-app',
                'platform' => 'web-only',
                'pair_slug' => null,
                'hub_group' => 'operations',
                'title' => 'Operations Management Web App',
                'short_title' => 'Operations Web App',
                'hub_title' => 'Operations Management Web App',
                'industry' => 'Services / Operations',
                'eyebrow' => 'Web Application Case Study',
                'platform_label' => 'Web Platform',
                'tagline' => 'Unified scheduling, invoicing, and reporting — replacing spreadsheet chaos with one operations platform.',
                'overview' => 'A services company was drowning in spreadsheets. We built a unified operations web application that put scheduling, invoicing, payment tracking, and reporting in one role-based platform for staff and management.',
                'overview_extra' => 'Teams gained dashboards, automated invoicing, and exportable insights — cutting manual work and operational cost.',
                'challenge_intro' => 'Scheduling lived in sheets, invoices were rebuilt every month, and managers had no live view of utilization or receivables.',
                'solution_intro' => 'A custom operations web app with role-based access, scheduling boards, automated invoicing, payment tracking, and a reporting suite.',
                'hero_image' => 'assets/images/portfolio6.jpg',
                'dashboard_image' => 'assets/images/case-studies/operations-management-web-app-web-dashboard.png',
                'admin_image' => 'assets/images/case-studies/operations-management-web-app-admin-portal.png',
                'mobile_screens_image' => null,
                'accent' => '#6d4df6',
                'challenges' => [
                    'Spreadsheet-driven scheduling',
                    'Manual invoicing and follow-ups',
                    'No shared source of truth for jobs',
                    'Weak visibility into utilization',
                    'Payment status scattered across tools',
                    'Reporting assembled by hand each week',
                ],
                'solution' => 'Delivered an operations management web app with staff and management dashboards, scheduling, automated invoicing, payment tracking, and exportable reporting.',
                'workflow' => [
                    'Job / service request',
                    'Schedule & assign',
                    'Work execution',
                    'Time & materials capture',
                    'Invoice generation',
                    'Payment tracking',
                    'Exception handling',
                    'Management reports',
                ],
                'modules' => [
                    'Scheduling' => ['Boards', 'Assignments', 'Capacity view'],
                    'Workforce' => ['Roles', 'Staff profiles', 'Utilization'],
                    'Invoicing' => ['Templates', 'Automation', 'Reminders'],
                    'Payments' => ['Status tracking', 'Reconciliation hooks'],
                    'Reporting' => ['Ops KPIs', 'Exports', 'Management packs'],
                    'Admin' => ['RBAC', 'Audit log', 'Settings'],
                ],
                'role_journeys' => [
                    ['role' => 'Dispatcher', 'journey' => 'Create job → assign crew → track completion'],
                    ['role' => 'Finance', 'journey' => 'Generate invoice → track payment → export'],
                    ['role' => 'Manager', 'journey' => 'Review utilization → clear exceptions → coach teams'],
                ],
                'roles' => [
                    ['name' => 'Staff', 'desc' => 'Assigned work and updates'],
                    ['name' => 'Dispatcher', 'desc' => 'Scheduling and assignments'],
                    ['name' => 'Finance', 'desc' => 'Invoices and payments'],
                    ['name' => 'Management', 'desc' => 'Dashboards and reporting'],
                ],
                'integrations' => ['Email notifications', 'Payment status hooks', 'Accounting export', 'Calendar sync'],
                'security' => ['Role-based dashboards', 'Segregation of finance actions', 'Audit trail', 'SSO-ready'],
                'delivery_highlights' => ['Spreadsheet replacement', 'Automated invoicing', 'Role-based UX', 'Exportable insights'],
                'tech_stack' => ['React', 'Node.js', 'PostgreSQL', 'AWS', 'PDF invoicing', 'SSO'],
                'mobile_apps' => [],
                'features' => ['Role-based Dashboards', 'Scheduling Board', 'Automated Invoicing', 'Payment Tracking', 'Reporting Suite', 'Audit Log'],
                'benefits' => ['Less manual work', 'Lower ops cost', 'Live management visibility', 'Faster invoicing cycles'],
                'results' => [['60%', 'Less manual work'], ['30%', 'Cost reduction'], ['4.9/5', 'User rating'], ['1', 'Ops system of record']],
                'future_scope' => ['Field mobile companion', 'AI schedule suggestions', 'Customer portal', 'Deeper ERP sync'],
                'related' => ['ecommerce-platform', 'travel-expense-management', 'invoice-management-system'],
            ],

            /* ——— CLASSIC: CUSTOMER MOBILE APP ——— */
            'customer-facing-mobile-app' => [
                'slug' => 'customer-facing-mobile-app',
                'platform' => 'web-only',
                'pair_slug' => null,
                'hub_group' => 'consumer-mobile',
                'title' => 'Customer-Facing Mobile App',
                'short_title' => 'Customer Mobile App',
                'hub_title' => 'Customer-Facing Mobile App',
                'industry' => 'Consumer / Retail',
                'eyebrow' => 'Mobile Apps Case Study',
                'platform_label' => 'Mobile Apps',
                'tagline' => 'Booking and loyalty app for iOS & Android — from prototype to store launch on one codebase.',
                'overview' => 'From prototype to app-store launch, we shipped a booking and loyalty mobile application for a consumer brand on both iOS and Android from a single React Native codebase — with push notifications, rewards, and seamless payment-backed booking.',
                'overview_extra' => 'The app drove downloads, repeat bookings, and strong store ratings while giving the brand a direct customer channel.',
                'challenge_intro' => 'The brand relied on web and third-party booking with weak loyalty loops and no owned push channel to bring customers back.',
                'solution_intro' => 'A cross-platform mobile app with booking, payments, loyalty rewards, and push — designed for store launch quality and retention.',
                'hero_image' => 'assets/images/portfolio8.jpg',
                'dashboard_image' => null,
                'admin_image' => 'assets/images/case-studies/customer-facing-mobile-app-admin-portal.png',
                'mobile_screens_image' => 'assets/images/case-studies/customer-facing-mobile-app-mobile-screens.png',
                'accent' => '#2f6bff',
                'challenges' => [
                    'No owned mobile booking experience',
                    'Fragmented loyalty across channels',
                    'Weak re-engagement without push',
                    'Separate iOS/Android would inflate cost',
                    'Checkout drop-off on mobile web',
                    'Limited insight into repeat behavior',
                ],
                'solution' => 'Built a React Native booking and loyalty app for iOS and Android with push notifications, rewards, and payment-integrated booking flows, plus a light admin console for offers and content.',
                'workflow' => [
                    'App install & signup',
                    'Browse services / slots',
                    'Book & pay',
                    'Confirmation & reminders',
                    'Visit / fulfillment',
                    'Loyalty points',
                    'Push re-engagement',
                    'Repeat booking',
                ],
                'modules' => [
                    'Booking' => ['Slot picker', 'Payments', 'Confirmations'],
                    'Loyalty' => ['Points', 'Rewards', 'Tiers'],
                    'Engagement' => ['Push', 'In-app offers', 'Deep links'],
                    'Profile' => ['History', 'Preferences', 'Support'],
                    'Admin Lite' => ['Offers', 'Content', 'Campaign hooks'],
                ],
                'role_journeys' => [
                    ['role' => 'Customer', 'journey' => 'Discover → book → earn points → return via push'],
                    ['role' => 'Brand Ops', 'journey' => 'Publish offer → monitor bookings → tune loyalty'],
                ],
                'roles' => [
                    ['name' => 'Customer', 'desc' => 'Book, pay, and redeem rewards'],
                    ['name' => 'Brand Admin', 'desc' => 'Offers and engagement content'],
                    ['name' => 'Support', 'desc' => 'Booking issues and refunds'],
                ],
                'integrations' => ['Payment SDK', 'Push (FCM / APNs)', 'Analytics', 'CRM / email'],
                'security' => ['Secure auth sessions', 'Tokenized payments', 'Privacy-safe analytics'],
                'delivery_highlights' => ['Single codebase iOS+Android', 'Store-ready QA', 'Push + loyalty', 'Payment booking'],
                'tech_stack' => ['React Native', 'Node.js', 'PostgreSQL', 'Firebase', 'Payment SDK', 'CDN'],
                'mobile_apps' => ['Customer iOS App', 'Customer Android App'],
                'features' => ['Cross-platform App', 'Booking & Payments', 'Loyalty Rewards', 'Push Notifications', 'Deep Links', 'Admin Offers'],
                'benefits' => ['Owned customer channel', 'Higher repeat bookings', 'Lower dual-app cost', 'Stronger engagement'],
                'results' => [['25k+', 'Downloads'], ['40%', 'Repeat bookings'], ['4.8★', 'Store rating'], ['1', 'Codebase for two stores']],
                'future_scope' => ['Wallet passes', 'Referral program', 'In-app chat', 'Personalization'],
                'related' => ['ecommerce-platform', 'operations-management-web-app', 'ev-charger-installation-mobile'],
            ],
        ];

        return $cases;
    }
}

if (!function_exists('case_study_get')) {
    function case_study_get(string $slug): ?array
    {
        $all = case_studies_all();
        if (!isset($all[$slug])) {
            return null;
        }
        $cs = $all[$slug];
        require_once __DIR__ . '/case-studies-narratives.php';
        $narratives = case_study_narratives();
        if (isset($narratives[$slug])) {
            $cs = array_merge($cs, $narratives[$slug]);
        }
        return $cs;
    }
}

if (!function_exists('case_studies_list')) {
    /** All individual case pages (web + mobile + web-only). */
    function case_studies_list(): array
    {
        return array_values(case_studies_all());
    }
}

if (!function_exists('case_studies_hub_groups')) {
    /**
     * Hub cards grouped by product (dual platforms share one card).
     * @return list<array{group:string,title:string,industry:string,tagline:string,hero:string,web:?array,mobile:?array,single:?array}>
     */
    function case_studies_hub_groups(): array
    {
        $groups = [];
        foreach (case_studies_all() as $cs) {
            $g = $cs['hub_group'];
            if (!isset($groups[$g])) {
                $groups[$g] = [
                    'group' => $g,
                    'title' => $cs['hub_title'],
                    'industry' => $cs['industry'],
                    'tagline' => '',
                    'hero' => $cs['hero_image'],
                    'web' => null,
                    'mobile' => null,
                    'single' => null,
                ];
            }
            if ($cs['platform'] === 'web') {
                $groups[$g]['web'] = $cs;
                $groups[$g]['hero'] = $cs['hero_image'];
                $groups[$g]['tagline'] = $cs['tagline'];
            } elseif ($cs['platform'] === 'mobile') {
                $groups[$g]['mobile'] = $cs;
                if ($groups[$g]['tagline'] === '') {
                    $groups[$g]['tagline'] = $cs['tagline'];
                }
            } else {
                $groups[$g]['single'] = $cs;
                $groups[$g]['hero'] = $cs['hero_image'];
                $groups[$g]['tagline'] = $cs['tagline'];
            }
        }
        return array_values($groups);
    }
}
