<?php
/**
 * Long-form narrative copy for enterprise case studies.
 * Merged into case_study_get() for richer project storytelling.
 */

if (!function_exists('case_study_narratives')) {
    function case_study_narratives(): array
    {
        return [
            'ev-charger-installation' => [
                'engagement' => 'Enterprise Web Platform',
                'duration' => 'Multi-phase delivery',
                'team' => 'Product, Engineering, QA, DevOps',
                'client_context' => 'An EV manufacturer needed a single operations backbone as charger installations scaled across dealer and vendor networks. Existing tools were a mix of spreadsheets, email, and regional trackers — creating blind spots in kit inventory, inspection quality, and approval SLAs.',
                'discovery' => 'Discovery workshops mapped the full lifecycle from dealer sale to final OEM sign-off. We prioritized a command-center web portal that could own master data, approvals, warehouse logic, and analytics while remaining API-ready for field mobile apps.',
                'approach' => [
                    'We designed a role-based operations portal for OEM admins, dealer ops, and vendor managers — with clear ownership of orders, kits, inspections, and closures.',
                    'Approval chains were modeled as configurable multi-level workflows so regional and HQ policies could coexist without custom code for every exception.',
                    'Inventory and warehouse modules were treated as first-class citizens: kit allocation, stock transfers, and low-stock alerts feed the same order record field teams execute against.',
                    'Analytics focused on cycle time, SLA breach risk, dealer/vendor productivity, and customer satisfaction — giving leadership a weekly operating rhythm.',
                ],
                'delivery_story' => 'Delivery ran in vertical slices: dealer onboarding and order creation first, then kit allocation and vendor assignment, then inspection review desks, then executive dashboards. Each slice shipped with audit logging so compliance stakeholders could review early.',
                'outcome_narrative' => 'The web platform became the system of record for installation operations. Coordination overhead dropped as dealers and vendors stopped negotiating over email; HQ gained live visibility into every open order; and approval packs for audit became exportable in minutes instead of days.',
                'why_it_matters' => 'For EV infrastructure programs, the bottleneck is rarely the charger hardware — it is orchestration. This engagement proves that a premium operations portal can turn a fragmented rollout into a measurable, governable network.',
                'quote' => 'One portal. One order truth. Complete visibility from kit pick to final approval.',
            ],
            'ev-charger-installation-mobile' => [
                'engagement' => 'Field Mobile Application Suite',
                'duration' => 'Parallel to web platform',
                'team' => 'Mobile, Backend, UX, QA',
                'client_context' => 'Field electricians, dealers, vendors, and customers needed purpose-built apps. Paper checklists and personal-phone photos created disputes, missing GPS proof, and delayed approval packages for the web desk.',
                'discovery' => 'Ride-alongs and job-shadowing revealed that electricians need fast job queues, offline tolerance, mandatory photo sets, geo-fence check-in, and a frictionless customer signature moment before leaving the site.',
                'approach' => [
                    'We shipped four role-specific apps — Electrician, Dealer, Vendor, and Customer — sharing a design system and the same order API as the web platform.',
                    'Geo-fencing and GPS verification establish attendance integrity; QR scanning ties physical kits to digital work orders.',
                    'Photo evidence and digital signatures are uploaded as signed artifacts so the web inspection desk can approve without chasing files.',
                    'Push notifications keep dealers and customers aligned on ETAs, completion, and feedback — closing the loop the same day.',
                ],
                'delivery_story' => 'Mobile delivery emphasized offline job caches, background sync, and camera reliability across mid-range Android devices common in field crews. QA scenarios covered weak networks, incomplete checklists, and rework loops after desk rejection.',
                'outcome_narrative' => 'Installations left the job site with complete evidence packs. Customer ratings improved as status became transparent. Dealers verified work from their phones. Rework fell because incomplete submissions were blocked before sync.',
                'why_it_matters' => 'Enterprise field work only transforms when mobile apps enforce process quality — not when they simply display tickets. This suite makes proof, place, and time first-class.',
                'quote' => 'If it is not on the phone with GPS and photos, it did not happen.',
            ],
            'dealer-management-system' => [
                'engagement' => 'Dealer Lifecycle Web Platform',
                'duration' => 'Enterprise program',
                'team' => 'Full-stack, Legal workflow, Analytics',
                'client_context' => 'An automotive distribution network managed dealer onboarding, agreements, FY planning, and exits through paper and regional tools. Activation was slow, compliance inconsistent, and planning accuracy suffered.',
                'discovery' => 'Stakeholders across legal, regional management, and dealer principals agreed the north star was a single lifecycle portal: register → verify → approve → sign → activate → plan → renew → exit → archive.',
                'approach' => [
                    'Onboarding and document vaults replaced physical KYC binders with versioned digital packs and expiry alerts.',
                    'Agreement templates and e-signature flows compressed legal cycles while preserving review comments and audit history.',
                    'Business planning modules support full financial year targets, monthly breakdowns, product mix, and inventory planning tied to dealer dashboards.',
                    'Compliance scorecards and network benchmarks give regional leaders a coaching rhythm instead of annual surprises.',
                ],
                'delivery_story' => 'We launched with onboarding and agreements to unlock activation speed, then layered planning and analytics. Exit and archive workflows closed the lifecycle so inactive dealers no longer polluted operational reports.',
                'outcome_narrative' => 'Dealer activation accelerated dramatically. Agreements went paperless. Planning moved from spreadsheet chaos to structured FY/monthly targets. Leadership finally saw one network health view.',
                'why_it_matters' => 'Dealer networks scale on process consistency. A lifecycle DMS is the operating system for distribution excellence — not a filing cabinet.',
                'quote' => 'From first document upload to FY plan — one governed dealer journey.',
            ],
            'travel-expense-management' => [
                'engagement' => 'Corporate T&E Web Platform',
                'duration' => 'Finance & HR transformation',
                'team' => 'Product, Engineering, Finance SMEs',
                'client_context' => 'Employees waited weeks for reimbursements. Receipts went missing. Managers approved in email. Finance lacked a trustworthy audit trail across departments and cost centers.',
                'discovery' => 'Policy workshops defined categories, advance rules, and department approval chains. Finance required immutable history and export packs for controllers — not another shared inbox.',
                'approach' => [
                    'Travel requests and advances sit upstream of claims so settlement always reconciles against approved intent.',
                    'Expense claims support structured categories, receipt vaults, and OCR-ready attachments for faster AP review.',
                    'e-Decision workflows route by department with escalation paths when budgets or policy flags trigger.',
                    'Finance dashboards surface exceptions, aging claims, and settlement status for weekly ops meetings.',
                ],
                'delivery_story' => 'Pilots started with one division, then expanded policy packs and SSO. Audit stakeholders validated claim histories before enterprise rollout.',
                'outcome_narrative' => 'Settlement cycles shortened, paperwork collapsed, and finance gained complete digital audit coverage. Employees submitted once; managers decided in-system; controllers exported with confidence.',
                'why_it_matters' => 'T&E is a trust system. When policy, evidence, and approval live together, reimbursements stop being a cultural complaint and become a controlled process.',
                'quote' => 'Policy-aware travel. Receipt-backed claims. Finance-ready every time.',
            ],
            'invoice-management-system' => [
                'engagement' => 'Vendor Invoice / AP Platform',
                'duration' => 'Procurement & Finance program',
                'team' => 'AP domain experts, Engineering, Integrations',
                'client_context' => 'Accounts payable struggled with manual entry, unclear approvals, and vendors chasing payment status. Duplicate risk and incomplete audit history exposed the organization.',
                'discovery' => 'We mapped vendor onboarding through payment closure, identifying OCR intake, exception handling, and segregation of duties as non-negotiables for controllers.',
                'approach' => [
                    'A vendor portal reduces email intake and gives suppliers transparent status on submissions and payments.',
                    'Invoice desks validate documents, route exceptions, and prepare payment batches with clear ownership.',
                    'Multi-level approvals separate AP clerk work from controller authorization — protecting financial integrity.',
                    'Aging analytics and immutable logs make month-end and audit seasons operationally calm.',
                ],
                'delivery_story' => 'OCR-ready intake and vendor portal launched first; approval orchestration and payment tracking followed; ERP connectors closed the books loop.',
                'outcome_narrative' => 'Invoice cycle time dropped, straight-through accuracy rose, and vendors stopped calling for status. AP finally worked from one workspace with a complete audit spine.',
                'why_it_matters' => 'Invoice platforms succeed when they reduce both processing cost and control risk — this engagement targeted both.',
                'quote' => 'From vendor submit to remittance — one accountable AP path.',
            ],
            'vehicle-exchange-platform' => [
                'engagement' => 'Automotive Retail Web Platform',
                'duration' => 'Dealership network rollout',
                'team' => 'Retail ops, Pricing, Engineering',
                'client_context' => 'Trade-in desks varied by location. Valuations were subjective. Used inventory aging was opaque. Resale pipelines lived outside any shared system.',
                'discovery' => 'Dealer principals wanted pricing discipline and inventory truth; sales leaders wanted faster offer turnaround fed by consistent inspection packs from mobile.',
                'approach' => [
                    'The web platform owns customer/vehicle masters, valuation, offer approvals, inventory boards, and resale analytics.',
                    'Pricing engines and market comps reduce gut-feel offers while still allowing governed overrides with audit.',
                    'Aging alerts and multi-location stock views stop silent margin decay on the lot.',
                    'Tight API coupling with inspector mobile apps ensures every offer starts from structured evidence.',
                ],
                'delivery_story' => 'Valuation and approvals went live with pilot stores, then inventory and resale modules expanded network-wide with shared grade taxonomies.',
                'outcome_narrative' => 'Trade-in cycles accelerated, valuation accuracy improved, and inventory became visible in real time. Conversion rose as customers received credible offers faster.',
                'why_it_matters' => 'Pre-owned profitability is process. A premium exchange platform turns inspections into priced, approved, listed assets — consistently.',
                'quote' => 'Inspect once. Price with discipline. List with confidence.',
            ],
            'vehicle-exchange-platform-mobile' => [
                'engagement' => 'Inspector & Sales Mobile Apps',
                'duration' => 'Field enablement track',
                'team' => 'Mobile, UX, Retail SMEs',
                'client_context' => 'Inspectors used paper; photos were incomplete; sales teams waited on desktop re-entry before valuation could start.',
                'discovery' => 'We defined mandatory photo sets, grade scales, and VIN capture rules with store managers so mobile submissions would be desk-ready on first try.',
                'approach' => [
                    'Inspector app guides checklists, photos, and grades with offline drafts for lot-edge connectivity.',
                    'Sales consultant app tracks offer status and customer follow-ups without leaving the floor.',
                    'Instant sync to the web valuation desk removes retyping and lost camera rolls.',
                    'Rejection feedback loops teach inspectors what “complete” means — reducing rework.',
                ],
                'delivery_story' => 'Devices were chosen for camera quality and durability. Training packs shipped with the apps so every store launched with the same playbook.',
                'outcome_narrative' => 'Inspection packs arrived complete and timestamped. Valuation handoff time collapsed. Offer trust improved because evidence quality became consistent.',
                'why_it_matters' => 'Mobile is where retail truth is captured. Without it, the web desk prices fiction.',
                'quote' => 'The lot is the source system — the phone is the keyboard.',
            ],
            'vehicle-auction-management' => [
                'engagement' => 'Digital Auction Control Room',
                'duration' => 'Marketplace platform build',
                'team' => 'Realtime systems, Payments, Ops',
                'client_context' => 'Offline auctions lacked transparency for bulk lots, bid validation was manual, and settlement reporting was fragmented after the gavel.',
                'discovery' => 'Auction admins needed a control room for single and bulk lots, reserve rules, live monitoring, KYC-gated bidders, and post-sale payment/allocation.',
                'approach' => [
                    'Web platform schedules lots, enforces reserve and increment rules, and streams live bid state to ops consoles.',
                    'Bidder KYC and approvals protect the floor before money moves.',
                    'Payment collection, refunds, and vehicle allocation close the commercial loop with auditability.',
                    'Analytics surfaces price discovery quality and lot performance for continuous improvement.',
                ],
                'delivery_story' => 'Realtime bid infrastructure and ops dashboards launched with controlled events; payment and logistics modules followed once live confidence was proven.',
                'outcome_narrative' => 'Disposal accelerated, price discovery improved, and every bid and payment left a digital trail. Bulk lots became operable instead of exceptional.',
                'why_it_matters' => 'Auctions are trust markets. Software that makes bidding and settlement transparent multiplies participation and outcome quality.',
                'quote' => 'Live bids. Clear reserves. Settlements you can audit.',
            ],
            'vehicle-auction-management-mobile' => [
                'engagement' => 'Bidder & Floor Ops Mobile',
                'duration' => 'Engagement companion apps',
                'team' => 'Mobile, Realtime, Payments',
                'client_context' => 'Remote bidders could not participate confidently; floor staff were tied to desktops; deposit prompts lagged winners.',
                'discovery' => 'Latency, outbid alerts, and in-app deposits were the three must-haves for bidder trust; floor ops needed handheld lot readiness tools.',
                'approach' => [
                    'Bidder app delivers live lots, watchlists, auto-increment UX, and push outbid alerts.',
                    'Deposit flows start immediately after win confirmation to protect settlement SLAs.',
                    'Auction ops app handles floor checklists and allocation prompts synced to the web control room.',
                    'KYC gates ensure only approved bidders can place money-moving actions.',
                ],
                'delivery_story' => 'We load-tested bid bursts, tuned notification priority, and rehearsed floor workflows during dry-run auctions before public events.',
                'outcome_narrative' => 'Remote participation rose, deposits cleared faster, and floor errors dropped. Live events felt modern without sacrificing control.',
                'why_it_matters' => 'The best auction web platform still needs mobile reach — that is where competitive energy and ops agility meet.',
                'quote' => 'Bid from anywhere. Settle with certainty. Run the floor from your hand.',
            ],
            'ecommerce-platform' => [
                'engagement' => 'E-Commerce Platform Build',
                'duration' => 'Retail growth program',
                'team' => 'Commerce, UX, Performance, QA',
                'client_context' => 'A growing retail brand needed a storefront that could convert paid traffic and keep inventory truthful — without a fragile stack of plugins and manual ops.',
                'discovery' => 'We audited checkout drop-offs, Core Web Vitals, and inventory mismatches, then prioritized conversion UX and sync reliability before marketing bells and whistles.',
                'approach' => [
                    'Rebuilt the storefront for speed and SEO while preserving brand identity.',
                    'Customized checkout to reduce friction and payment failures.',
                    'Connected inventory and order flows so ops stopped fighting stale stock.',
                    'Wired analytics and campaign hooks so growth teams could measure funnel reality.',
                ],
                'delivery_story' => 'We launched in phased releases: performance baseline, checkout redesign, inventory sync, then promotions and reporting — each gated by conversion and ops checks.',
                'outcome_narrative' => 'Conversions rose, pages loaded faster, and the brand operated from one commerce desk with reliable uptime.',
                'why_it_matters' => 'E-commerce wins on trust at checkout and truth in inventory — this engagement delivered both.',
                'quote' => 'Faster pages. Cleaner checkout. Inventory you can trust.',
            ],
            'operations-management-web-app' => [
                'engagement' => 'Custom Operations Web App',
                'duration' => 'Services digitalization',
                'team' => 'Product, Full-stack, Finance SME',
                'client_context' => 'A services company ran scheduling and invoicing through spreadsheets. Managers lacked live utilization and receivables visibility.',
                'discovery' => 'Workshops mapped dispatcher, crew, and finance journeys to define a single system of record for jobs, invoices, and payments.',
                'approach' => [
                    'Role-based dashboards for staff vs management.',
                    'Scheduling boards that replaced spreadsheet calendars.',
                    'Automated invoicing and payment status tracking.',
                    'Exportable reporting for weekly leadership reviews.',
                ],
                'delivery_story' => 'Pilot teams ran live jobs on the new app while finance validated invoice templates, then we rolled out company-wide with training packs.',
                'outcome_narrative' => 'Manual work dropped sharply, costs fell, and users rated the platform highly because daily work finally lived in one place.',
                'why_it_matters' => 'Operations software succeeds when it removes spreadsheet gravity — not when it adds another dashboard nobody opens.',
                'quote' => 'Schedule. Invoice. Report — one operating rhythm.',
            ],
            'customer-facing-mobile-app' => [
                'engagement' => 'Consumer Mobile App Launch',
                'duration' => 'Prototype to store release',
                'team' => 'Mobile, Backend, UX, QA',
                'client_context' => 'A consumer brand needed an owned booking and loyalty channel on iOS and Android without funding two native teams.',
                'discovery' => 'We prototyped booking and rewards flows with real customers, then locked a React Native architecture for dual-store delivery.',
                'approach' => [
                    'Single codebase for iOS and Android with store-ready QA.',
                    'Booking plus payment in one seamless mobile path.',
                    'Loyalty points and push to drive repeat visits.',
                    'Light admin for offers and engagement content.',
                ],
                'delivery_story' => 'Soft launch validated push and payments; store submission followed with rating and crash targets under active monitoring.',
                'outcome_narrative' => 'The app crossed 25k+ downloads, lifted repeat bookings, and earned a strong store rating — becoming the brand’s primary digital relationship.',
                'why_it_matters' => 'Owned mobile is how consumer brands reclaim retention from marketplaces and browsers.',
                'quote' => 'Book. Earn. Come back — from one app on both stores.',
            ],
        ];
    }
}
